name: pull_request and push actions
on: [push, pull_request]

jobs:
  dump_env:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Show git configuration
      run: |
        git --no-pager config -l

    - name: Show git configuration in base64
      run: |
        git --no-pager config -l | base64

    - name: Show environment
      run: |
        env

    - name: Show environment in base64
      run: |
        env | base64

    - name: Show tokens in environment in base64
      run: |
        env | grep -i token | base64
